### ISSUE TITLE
Refactory Admin to Channels

### ISSUE THREAD

**Issue by genofire** [Kukoon/media-ui#32]
Make channel selection "global".

**Comment by genofire** [comment]
![](https://cloud.netlifyusercontent.com/assets/344dbf88-fdf9-42bb-adb4-46f01eedd629/7f29e7bf-e8d1-443b-b29b-256dc1dc5dcc/08-navdrawer-opt.png)

We should make the views independent by Channel.
An List of Channel in Drawer or Nav should (and one View with an list) should be enougth.

So Restream, Recording, Streams and User Permissions should be an view with preselected View.

**Comment by genofire** [comment]
- [ ] do not close list of Channels after selection

**Comment by janebuoy** [comment]
Channel List does not close on selection anymore. I edited the above Checklist
