### ISSUE TITLE
Errors on api.Streams.Delete

### ISSUE THREAD

**Issue by janebuoy** [Kukoon/media-ui#49]
Deletion of Stream from StreamSchedule throws 404 Error for GET request https://v2-dev.media.kukoon.de/api/v1/stream/STREAMID

**Comment by genofire** [comment]
A delete should be a "Delete request" .... hmm strange, last time it works. I have to take a lock

**Comment by genofire** [comment]
okay, it makes a unessasary request in background - good finding

**Comment by genofire** [comment]
looks for me like solved
