### ISSUE TITLE
Dynamic Landing Page

### ISSUE THREAD

**Issue by janebuoy** [Kukoon/media-ui#7]
Land on 'Live' or 'Recordings' depending on if there is a live stream

**Comment by genofire** [comment]
The API should solve it already (not fully working ATM) - if the count of streams is 0 there is no live stream
`/api/v1/streams?running=true`

or if `defaultChannel` in `config.js` is set
`/api/v1/streams?running=true&channel=df1555f5-7046-4f7a-adcc-195b73949723`

**Comment by genofire** [comment]
#27 

maybe also an Upcoming Streams?

**Comment by genofire** [comment]
upcoming are now visible to ;)

for me this issue could be closed
